/**
 * Official Invidious API Client
 * Documentation: https://docs.invidious.io/api/
 * Full implementation covering all Invidious /api/v1 endpoints and data structures
 */

export interface InvidiousThumbnail {
  quality?: string;
  url: string;
  width?: number;
  height?: number;
}

export interface InvidiousFormatStream {
  url: string;
  itag: string;
  type: string;
  quality: string;
  fps?: number;
  container?: string;
  encoding?: string;
  resolution?: string;
  qualityLabel?: string;
  size?: string;
}

export interface InvidiousAdaptiveFormat {
  init?: string;
  index?: string;
  bitrate?: string;
  url: string;
  itag: string;
  type: string;
  clen?: string;
  lmt?: string;
  projectionType?: number;
  container?: string;
  encoding?: string;
  qualityLabel?: string;
  resolution?: string;
  audioQuality?: string;
  audioSampleRate?: number;
  audioChannels?: number;
  fps?: number;
  size?: string;
}

export interface InvidiousCaption {
  label: string;
  languageCode: string;
  url: string;
}

export interface InvidiousVideo {
  type?: string;
  title: string;
  videoId: string;
  videoThumbnails: InvidiousThumbnail[];
  description: string;
  descriptionHtml: string;
  published: number;
  publishedText: string;
  keywords: string[];
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  paid: boolean;
  premium: boolean;
  isFamilyFriendly: boolean;
  allowedRegions: string[];
  genre: string;
  genreUrl: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: InvidiousThumbnail[];
  subCountText: string;
  lengthSeconds: number;
  allowRatings: boolean;
  rating: number;
  isListed: boolean;
  liveNow: boolean;
  isUpcoming: boolean;
  premiereTimestamp?: number;
  hlsUrl?: string;
  adaptiveFormats: InvidiousAdaptiveFormat[];
  formatStreams: InvidiousFormatStream[];
  captions: InvidiousCaption[];
  recommendedVideos: InvidiousVideo[];
}

export interface InvidiousComment {
  author: string;
  authorThumbnails: InvidiousThumbnail[];
  authorId: string;
  authorUrl: string;
  isEdited: boolean;
  isPinned: boolean;
  content: string;
  contentHtml: string;
  published: number;
  publishedText: string;
  likeCount: number;
  commentId: string;
  authorIsChannelOwner: boolean;
  creatorReplied?: boolean;
  replies?: {
    replyCount: number;
    continuation: string;
  };
}

export interface InvidiousChannel {
  author: string;
  authorId: string;
  authorUrl: string;
  authorBanners: InvidiousThumbnail[];
  authorThumbnails: InvidiousThumbnail[];
  subCount: number;
  totalViews: number;
  joined: number;
  autoGenerated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: string[];
  tabs: string[];
  tags: string[];
  latestVideos?: InvidiousVideo[];
  relatedChannels?: Array<{ author: string; authorId: string; authorUrl: string; authorThumbnails: InvidiousThumbnail[] }>;
}

export interface InvidiousPlaylist {
  title: string;
  playlistId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: InvidiousThumbnail[];
  description?: string;
  descriptionHtml?: string;
  videoCount: number;
  viewCount?: number;
  updated?: number;
  isListed?: boolean;
  videos: Array<{
    title: string;
    videoId: string;
    author: string;
    authorId: string;
    authorUrl: string;
    videoThumbnails: InvidiousThumbnail[];
    index: number;
    lengthSeconds: number;
  }>;
}

export interface InvidiousStats {
  version: string;
  software: {
    name: string;
    version: string;
    branch: string;
  };
  openRegistrations: boolean;
  usage: {
    users: {
      total: number;
      activeHalfyear: number;
      activeMonth: number;
    };
  };
}

export interface SearchOptions {
  page?: number;
  sort_by?: 'relevance' | 'rating' | 'upload_date' | 'view_count';
  date?: 'hour' | 'today' | 'week' | 'month' | 'year' | '';
  duration?: 'short' | 'medium' | 'long' | '';
  type?: 'all' | 'video' | 'channel' | 'playlist' | 'movie' | 'show';
  features?: string;
  region?: string;
}

export class InvidiousService {
  private instanceUrl: string;

  constructor() {
    this.instanceUrl = process.env.NEXT_PUBLIC_INVIDIOUS_URL || 'https://yt.khoavo.myds.me';
    if (typeof window !== 'undefined') {
      const custom = localStorage.getItem('kv_invidious_instance');
      if (custom && custom.trim()) {
        this.instanceUrl = custom.replace(/\/$/, '');
      }
    }
  }

  public setInstanceUrl(url: string) {
    this.instanceUrl = url.replace(/\/$/, '');
    if (typeof window !== 'undefined') {
      localStorage.setItem('kv_invidious_instance', this.instanceUrl);
    }
  }

  public getInstanceUrl(): string {
    return this.instanceUrl;
  }

  public getToken(): string | null {
    if (typeof window === 'undefined') return null;
    return localStorage.getItem('kv_invidious_token');
  }

  public setToken(token: string | null) {
    if (typeof window === 'undefined') return;
    if (token) {
      localStorage.setItem('kv_invidious_token', token);
    } else {
      localStorage.removeItem('kv_invidious_token');
    }
  }

  private static readonly FALLBACK_INSTANCES = [
    'https://yewtu.be',
    'https://invidious.nerdvpn.de',
    'https://invidious.snopyta.org',
    'https://inv.tux.pizza',
  ];

  // Generic Public API fetcher with multi-node resilient fallback
  public async fetchApi<T>(endpoint: string, params: Record<string, any> = {}): Promise<T> {
    const instancesToTry = [
      this.instanceUrl,
      ...InvidiousService.FALLBACK_INSTANCES.filter(i => i !== this.instanceUrl),
    ];

    let lastError: any = null;

    for (const base of instancesToTry) {
      try {
        const url = new URL(`${base}/api/v1${endpoint}`);
        Object.entries(params).forEach(([key, val]) => {
          if (val !== undefined && val !== null && val !== '') {
            url.searchParams.set(key, String(val));
          }
        });

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 7000);

        const res = await fetch(url.toString(), {
          headers: {
            'Accept': 'application/json',
          },
          signal: controller.signal,
        });

        clearTimeout(timeoutId);

        if (res.ok) {
          return await res.json();
        }
      } catch (err: any) {
        lastError = err;
        continue;
      }
    }

    throw lastError || new Error(`All Invidious instances failed for ${endpoint}`);
  }

  // Generic Authenticated API fetcher
  public async fetchAuthApi<T>(
    endpoint: string,
    options: { method?: string; body?: any; params?: Record<string, any> } = {}
  ): Promise<T> {
    const token = this.getToken();
    const isBrowser = typeof window !== 'undefined';

    // In browser, route through our Next.js API server proxy to avoid CORS and forbidden-header ('Cookie') restrictions
    const baseUrl = isBrowser ? `/api/invidious/api/v1/auth${endpoint}` : `${this.instanceUrl}/api/v1/auth${endpoint}`;
    const url = new URL(baseUrl, isBrowser ? window.location.origin : this.instanceUrl);

    if (options.params) {
      Object.entries(options.params).forEach(([k, v]) => {
        if (v !== undefined && v !== null && v !== '') {
          url.searchParams.set(k, String(v));
        }
      });
    }

    const headers: Record<string, string> = {
      'Accept': 'application/json',
    };

    if (token) {
      const trimmed = token.trim();
      if (isBrowser) {
        headers['x-invidious-token'] = trimmed;
        if (trimmed.startsWith('{')) {
          headers['Authorization'] = `Bearer ${trimmed}`;
        }
      } else {
        if (trimmed.startsWith('{')) {
          headers['Authorization'] = `Bearer ${trimmed}`;
        } else {
          headers['Cookie'] = `SID=${trimmed}`;
        }
      }
    }

    if (options.body) {
      headers['Content-Type'] = 'application/json';
    }

    const res = await fetch(url.toString(), {
      method: options.method || 'GET',
      headers,
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    if (!res.ok) {
      let errMsg = `Invidious Auth API error (${res.status}): ${res.statusText}`;
      try {
        const errJson = await res.json();
        if (errJson?.error) errMsg = errJson.error;
      } catch {}
      throw new Error(errMsg);
    }

    return res.json();
  }

  // Test token against Invidious authenticated endpoints
  public async testAuthToken(customToken?: string): Promise<{ success: boolean; message: string; details?: any }> {
    const originalToken = this.getToken();
    if (customToken !== undefined) {
      this.setToken(customToken.trim());
    }

    try {
      const activeToken = this.getToken();
      if (!activeToken) {
        return { success: false, message: 'No token provided' };
      }

      // Try fetching subscriptions
      const subs = await this.getAuthSubscriptions();
      return {
        success: true,
        message: `Successfully connected to Invidious! Found ${Array.isArray(subs) ? subs.length : 0} subscriptions.`,
        details: { subscriptionsCount: Array.isArray(subs) ? subs.length : 0 },
      };
    } catch (err: any) {
      return {
        success: false,
        message: err?.message || 'Authentication failed',
      };
    } finally {
      if (customToken !== undefined) {
        this.setToken(originalToken);
      }
    }
  }

  // -------------------------------------------------------------
  // 1. INSTANCE STATS & HEALTH
  // -------------------------------------------------------------
  async getStats(): Promise<InvidiousStats> {
    return this.fetchApi('/stats');
  }

  async resolveUrl(url: string): Promise<any> {
    return this.fetchApi('/resolveurl', { url });
  }

  // -------------------------------------------------------------
  // 2. VIDEOS & PLAYBACK
  // -------------------------------------------------------------
  async getVideo(videoId: string, params?: { region?: string; hl?: string }): Promise<InvidiousVideo> {
    return this.fetchApi(`/videos/${encodeURIComponent(videoId)}`, params);
  }

  async getAnnotations(videoId: string): Promise<any> {
    return this.fetchApi(`/annotations/${encodeURIComponent(videoId)}`);
  }

  async getComments(
    videoId: string,
    continuation?: string,
    sort_by?: 'top' | 'new',
    format: 'html' | 'plain' = 'html'
  ): Promise<{ comments: InvidiousComment[]; continuation?: string }> {
    return this.fetchApi(`/comments/${encodeURIComponent(videoId)}`, {
      continuation,
      sort_by,
      format,
    });
  }

  async getCaptions(videoId: string, label?: string, lang?: string): Promise<any> {
    return this.fetchApi(`/captions/${encodeURIComponent(videoId)}`, { label, lang });
  }

  async getClips(videoId: string): Promise<any> {
    return this.fetchApi('/clips', { id: videoId });
  }

  // -------------------------------------------------------------
  // 3. DISCOVERY, TRENDING & FEEDS
  // -------------------------------------------------------------
  async getTrending(region: string = 'VN', type?: string): Promise<any[]> {
    return this.fetchApi('/trending', { region, type });
  }

  async getPopular(): Promise<any[]> {
    return this.fetchApi('/popular');
  }

  async getHashtag(tag: string, page: number = 1): Promise<any> {
    return this.fetchApi(`/hashtag/${encodeURIComponent(tag)}`, { page });
  }

  async getMixes(rdid: string): Promise<any> {
    return this.fetchApi(`/mixes/${encodeURIComponent(rdid)}`);
  }

  // -------------------------------------------------------------
  // 4. SEARCH
  // -------------------------------------------------------------
  async getSuggestions(query: string): Promise<string[]> {
    if (!query.trim()) return [];
    try {
      const res = await this.fetchApi<{ query: string; suggestions: string[] }>('/search/suggestions', {
        q: query,
      });
      return res.suggestions || [];
    } catch {
      return [];
    }
  }

  async search(query: string, options: SearchOptions = {}): Promise<any[]> {
    return this.fetchApi('/search', {
      q: query,
      page: options.page || 1,
      sort_by: options.sort_by || 'relevance',
      date: options.date || '',
      duration: options.duration || '',
      type: options.type || 'all',
      features: options.features || '',
      region: options.region || '',
    });
  }

  // -------------------------------------------------------------
  // 5. CHANNELS
  // -------------------------------------------------------------
  async getChannel(channelId: string, hl?: string): Promise<InvidiousChannel> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}`, { hl });
  }

  async getChannelVideos(
    channelId: string,
    continuation?: string,
    sort_by: 'newest' | 'oldest' | 'popular' = 'newest'
  ): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/videos`, {
      continuation,
      sort_by,
    });
  }

  async getChannelShorts(channelId: string, continuation?: string): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/shorts`, { continuation });
  }

  async getChannelStreams(channelId: string, continuation?: string): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/streams`, { continuation });
  }

  async getChannelPlaylists(channelId: string, continuation?: string, sort_by?: string): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/playlists`, { continuation, sort_by });
  }

  async getChannelCommunity(channelId: string, continuation?: string): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/community`, { continuation });
  }

  async searchChannel(channelId: string, query: string, page: number = 1, sort_by: string = 'relevance'): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/search`, {
      q: query,
      page,
      sort_by,
    });
  }

  async getChannelLatest(channelId: string): Promise<any> {
    return this.fetchApi(`/channels/${encodeURIComponent(channelId)}/latest`);
  }

  // -------------------------------------------------------------
  // 6. PUBLIC PLAYLISTS
  // -------------------------------------------------------------
  async getPlaylist(playlistId: string, page: number = 1): Promise<InvidiousPlaylist> {
    return this.fetchApi(`/playlists/${encodeURIComponent(playlistId)}`, { page });
  }

  // -------------------------------------------------------------
  // 7. AUTHENTICATED USER ENDPOINTS (/api/v1/auth/)
  // -------------------------------------------------------------
  async getAuthFeed(page: number = 1, max_results?: number): Promise<any[]> {
    const res: any = await this.fetchAuthApi('/feed', { params: { page, max_results } });
    if (Array.isArray(res)) return res;
    if (Array.isArray(res?.videos)) return res.videos;
    return [];
  }

  async getAuthFeedUnseen(page: number = 1): Promise<any[]> {
    const res: any = await this.fetchAuthApi('/feed/unseen', { params: { page } });
    if (Array.isArray(res)) return res;
    if (Array.isArray(res?.videos)) return res.videos;
    return [];
  }

  async getAuthNotifications(): Promise<any[]> {
    const res: any = await this.fetchAuthApi('/notifications');
    return Array.isArray(res) ? res : [];
  }

  async markAuthNotifications(notificationIds?: string[]): Promise<boolean> {
    try {
      await this.fetchAuthApi('/notifications', { method: 'POST', body: { notificationIds } });
      return true;
    } catch {
      return false;
    }
  }

  async getAuthSubscriptions(): Promise<Array<{ author: string; authorId: string; authorUrl: string; authorThumbnails?: any[] }>> {
    const res: any = await this.fetchAuthApi('/subscriptions');
    if (Array.isArray(res)) return res;
    if (Array.isArray(res?.subscriptions)) return res.subscriptions;
    return [];
  }

  async subscribeChannel(channelId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/subscriptions/${encodeURIComponent(channelId)}`, { method: 'POST' });
      return true;
    } catch {
      return false;
    }
  }

  async unsubscribeChannel(channelId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/subscriptions/${encodeURIComponent(channelId)}`, { method: 'DELETE' });
      return true;
    } catch {
      return false;
    }
  }

  async getAuthHistory(page: number = 1): Promise<any[]> {
    const res: any = await this.fetchAuthApi('/history', { params: { page } });
    if (Array.isArray(res)) return res;
    if (Array.isArray(res?.videos)) return res.videos;
    return [];
  }

  async getAllAuthHistory(maxPages: number = 20): Promise<any[]> {
    const allVideos: any[] = [];
    const seen = new Set<string>();

    for (let p = 1; p <= maxPages; p++) {
      try {
        const pageItems = await this.getAuthHistory(p);
        if (!Array.isArray(pageItems) || pageItems.length === 0) break;

        let addedThisPage = 0;
        for (const item of pageItems) {
          const id = item.videoId || item.id;
          if (id && !seen.has(id)) {
            seen.add(id);
            allVideos.push(item);
            addedThisPage++;
          }
        }

        if (addedThisPage === 0 || pageItems.length < 5) break;
      } catch (err) {
        console.warn(`[getAllAuthHistory] Error on page ${p}:`, err);
        break;
      }
    }

    return allVideos;
  }

  async addAuthHistory(videoId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/history/${encodeURIComponent(videoId)}`, { method: 'POST' });
      return true;
    } catch {
      return false;
    }
  }

  async removeAuthHistory(videoId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/history/${encodeURIComponent(videoId)}`, { method: 'DELETE' });
      return true;
    } catch {
      return false;
    }
  }

  async getAuthPlaylists(): Promise<any[]> {
    const res: any = await this.fetchAuthApi('/playlists');
    if (Array.isArray(res)) return res;
    if (Array.isArray(res?.playlists)) return res.playlists;
    return [];
  }

  async createAuthPlaylist(title: string, privacy: 'public' | 'unlisted' | 'private' = 'private'): Promise<any> {
    return this.fetchAuthApi('/playlists', { method: 'POST', body: { title, privacy } });
  }

  async getAuthPlaylist(playlistId: string): Promise<any> {
    return this.fetchAuthApi(`/playlists/${encodeURIComponent(playlistId)}`);
  }

  async updateAuthPlaylist(playlistId: string, data: { title?: string; description?: string; privacy?: string }): Promise<any> {
    return this.fetchAuthApi(`/playlists/${encodeURIComponent(playlistId)}`, { method: 'PATCH', body: data });
  }

  async deleteAuthPlaylist(playlistId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/playlists/${encodeURIComponent(playlistId)}`, { method: 'DELETE' });
      return true;
    } catch {
      return false;
    }
  }

  async addVideoToAuthPlaylist(playlistId: string, videoId: string): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/playlists/${encodeURIComponent(playlistId)}/videos`, { method: 'POST', body: { videoId } });
      return true;
    } catch {
      return false;
    }
  }

  async removeVideoFromAuthPlaylist(playlistId: string, index: number): Promise<boolean> {
    try {
      await this.fetchAuthApi(`/playlists/${encodeURIComponent(playlistId)}/videos/${index}`, { method: 'DELETE' });
      return true;
    } catch {
      return false;
    }
  }

  async getAuthPreferences(): Promise<any> {
    return this.fetchAuthApi('/preferences');
  }

  async updateAuthPreferences(preferences: Record<string, any>): Promise<any> {
    return this.fetchAuthApi('/preferences', { method: 'POST', body: { preferences } });
  }

  async getAuthTokens(): Promise<any> {
    return this.fetchAuthApi('/tokens');
  }

  async registerAuthToken(session: string, scopes: string[] = ['*']): Promise<any> {
    return this.fetchAuthApi('/tokens/register', { method: 'POST', body: { session, scopes } });
  }

  async unregisterAuthToken(session: string): Promise<any> {
    return this.fetchAuthApi('/tokens/unregister', { method: 'POST', body: { session } });
  }

  // Push a single subscription to Invidious user account
  async pushSubscriptionToInvidious(channelId: string, customToken?: string): Promise<boolean> {
    const token = customToken || this.getToken();
    if (!token) return false;
    try {
      const res = await fetch(`${this.instanceUrl}/api/v1/auth/subscriptions/${encodeURIComponent(channelId)}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Cookie': `SID=${token}`,
          'Accept': 'application/json',
        },
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  // Parse any subscriptions format (Invidious JSON, NewPipe JSON, Google Takeout CSV, OPML XML)
  parseSubscriptions(content: string): Array<{ channelId: string; channelName: string; channelAvatar?: string }> {
    const list: Array<{ channelId: string; channelName: string; channelAvatar?: string }> = [];

    // 1. Try JSON formats (Invidious / NewPipe / FreeTube)
    try {
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (typeof item === 'string' && item.startsWith('UC')) {
            list.push({ channelId: item, channelName: item });
          } else if (item && typeof item === 'object') {
            const id = item.authorId || item.channel_id || item.channelId || item.id || item.url?.split('/').pop() || '';
            const name = item.author || item.channel_name || item.channelName || item.name || item.title || id;
            const avatar = item.authorThumbnails?.[0]?.url || item.avatar || '';
            if (id) list.push({ channelId: id, channelName: name, channelAvatar: avatar });
          }
        }
        if (list.length > 0) return list;
      } else if (parsed && typeof parsed === 'object' && Array.isArray(parsed.subscriptions)) {
        for (const item of parsed.subscriptions) {
          const id = item.url?.split('/').pop() || item.channelId || item.id || '';
          const name = item.name || item.title || id;
          if (id) list.push({ channelId: id, channelName: name });
        }
        if (list.length > 0) return list;
      }
    } catch {}

    // 2. Try Google Takeout CSV (Channel Id,Channel Url,Channel Title)
    const lines = content.split('\n');
    for (const line of lines) {
      if (line.includes('Channel Id') || !line.trim()) continue;
      const parts = line.split(',');
      if (parts.length >= 3 && parts[0].trim().startsWith('UC')) {
        const id = parts[0].trim();
        const name = parts.slice(2).join(',').replace(/^"|"$/g, '').trim();
        list.push({ channelId: id, channelName: name || id });
      }
    }
    if (list.length > 0) return list;

    // 3. Try OPML / XML regex
    const opmlMatches = content.matchAll(/xmlUrl="[^"]*channel_id=([a-zA-Z0-9_-]+)"[^>]*title="([^"]*)"/g);
    for (const match of opmlMatches) {
      if (match[1]) {
        list.push({ channelId: match[1], channelName: match[2] || match[1] });
      }
    }

    return list;
  }
}

export const invidious = new InvidiousService();
