package com.kvtube.tv.data.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// --- Mirrors frontend/app/services/invidious.ts ---

@JsonClass(generateAdapter = false)
data class InvidiousThumbnail(
    val quality: String? = null,
    val url: String = "",
    val width: Int? = null,
    val height: Int? = null,
)

@JsonClass(generateAdapter = false)
data class InvidiousFormatStream(
    val url: String = "",
    val itag: String = "",
    val type: String = "",
    val quality: String = "",
    val fps: Int? = null,
    val container: String? = null,
    val encoding: String? = null,
    val resolution: String? = null,
    val qualityLabel: String? = null,
    val size: String? = null,
)

@JsonClass(generateAdapter = false)
data class InvidiousAdaptiveFormat(
    val url: String = "",
    val itag: String = "",
    val type: String = "",
    val qualityLabel: String? = null,
    val resolution: String? = null,
    val container: String? = null,
    val encoding: String? = null,
    val bitrate: String? = null,
    val fps: Int? = null,
    val audioQuality: String? = null,
    val audioSampleRate: Int? = null,
    val audioChannels: Int? = null,
)

@JsonClass(generateAdapter = false)
data class InvidiousCaption(
    val label: String = "",
    val languageCode: String = "",
    val url: String = "",
)

@JsonClass(generateAdapter = false)
data class InvidiousVideo(
    val type: String? = null,
    val title: String = "",
    val videoId: String = "",
    val videoThumbnails: List<InvidiousThumbnail> = emptyList(),
    val description: String? = null,
    val descriptionHtml: String? = null,
    val published: Long? = null,
    val publishedText: String? = null,
    val keywords: List<String> = emptyList(),
    val viewCount: Long? = null,
    val likeCount: Long? = null,
    val dislikeCount: Long? = null,
    val author: String? = null,
    val authorId: String? = null,
    val authorUrl: String? = null,
    val authorThumbnails: List<InvidiousThumbnail> = emptyList(),
    val subCountText: String? = null,
    val lengthSeconds: Int = 0,
    val liveNow: Boolean = false,
    val isUpcoming: Boolean? = null,
    val dashUrl: String? = null,
    val hlsUrl: String? = null,
    val adaptiveFormats: List<InvidiousAdaptiveFormat> = emptyList(),
    val formatStreams: List<InvidiousFormatStream> = emptyList(),
    val captions: List<InvidiousCaption> = emptyList(),
    val recommendedVideos: List<InvidiousVideo> = emptyList(),
    val genre: String? = null,
    val genreUrl: String? = null,
)

@JsonClass(generateAdapter = false)
data class InvidiousChannel(
    val author: String = "",
    val authorId: String = "",
    val authorUrl: String = "",
    val authorBanners: List<InvidiousThumbnail> = emptyList(),
    val authorThumbnails: List<InvidiousThumbnail> = emptyList(),
    val subCount: Long? = null,
    val totalViews: Long? = null,
    val joined: Long? = null,
    val autoGenerated: Boolean? = null,
    val isFamilyFriendly: Boolean? = null,
    val description: String? = null,
    val descriptionHtml: String? = null,
    val allowedRegions: List<String> = emptyList(),
    val latestVideos: List<InvidiousVideo> = emptyList(),
    val relatedChannels: List<InvidiousChannel> = emptyList(),
)

@JsonClass(generateAdapter = false)
data class InvidiousPlaylist(
    val title: String = "",
    val playlistId: String = "",
    val author: String? = null,
    val authorId: String? = null,
    val authorThumbnails: List<InvidiousThumbnail> = emptyList(),
    val description: String? = null,
    val descriptionHtml: String? = null,
    val videoCount: Int? = null,
    val viewCount: Long? = null,
    val updated: Long? = null,
    val videos: List<InvidiousVideo> = emptyList(),
)

@JsonClass(generateAdapter = false)
data class InvidiousPlaylistVideo(
    val title: String = "",
    val videoId: String = "",
    val author: String? = null,
    val authorId: String? = null,
    val authorUrl: String? = null,
    val videoThumbnails: List<InvidiousThumbnail> = emptyList(),
    val index: Int? = null,
    val lengthSeconds: Int = 0,
)

@JsonClass(generateAdapter = false)
data class InvidiousComment(
    val author: String = "",
    val authorThumbnails: List<InvidiousThumbnail> = emptyList(),
    val authorId: String = "",
    val authorUrl: String = "",
    val content: String = "",
    val contentHtml: String = "",
    val published: Long = 0,
    val publishedText: String = "",
    val likeCount: Int = 0,
    val commentId: String = "",
    val authorIsChannelOwner: Boolean = false,
)

@JsonClass(generateAdapter = false)
data class SearchResultItem(
    val type: String = "",
    val title: String? = null,
    val videoId: String? = null,
    val author: String? = null,
    val authorId: String? = null,
    val authorUrl: String? = null,
    val videoThumbnails: List<InvidiousThumbnail>? = null,
    val description: String? = null,
    val descriptionHtml: String? = null,
    val viewCount: Long? = null,
    val published: Long? = null,
    val publishedText: String? = null,
    val lengthSeconds: Int? = null,
    val liveNow: Boolean? = null,
    val paid: Boolean? = null,
    val premium: Boolean? = null,
    // channel result fields
    val authorThumbnails: List<InvidiousThumbnail>? = null,
    val subCount: Long? = null,
    val videoCount: Int? = null,
)

// Light adapter for TV rows/cards — mirrors frontend VideoData / mapInvidiousVideo
data class TvVideo(
    val id: String,
    val title: String,
    val channelTitle: String,
    val channelId: String,
    val thumbnail: String,
    val duration: String,
    val viewsText: String?,
    val publishedText: String?,
    val avatarUrl: String?,
    val isLive: Boolean = false,
)

fun InvidiousVideo.toTvVideo(): TvVideo {
    val id = videoId.ifBlank { "" }
    // Invidious returns http://yt.khoavo.myds.me/vi/... which times out in Waydroid/container.
    // Force i.ytimg.com (same as web frontend) — always https and reachable.
    val thumb = if (id.isNotBlank()) "https://i.ytimg.com/vi/$id/mqdefault.jpg" else ""
    val dur = if (lengthSeconds > 0) {
        val m = lengthSeconds / 60
        val s = lengthSeconds % 60
        "%d:%02d".format(m, s)
    } else ""
    val avatar = authorThumbnails.firstOrNull()?.url ?: authorThumbnails.lastOrNull()?.url
    val views = viewCount?.takeIf { it > 0 }?.let { formatViews(it) }
    return TvVideo(
        id = id,
        title = title.ifBlank { "Untitled" },
        channelTitle = author ?: "Unknown",
        channelId = authorId ?: "",
        thumbnail = thumb,
        duration = dur,
        viewsText = views,
        publishedText = publishedText,
        avatarUrl = fixThumbnailUrl(avatar),
        isLive = liveNow,
    )
}

fun SearchResultItem.toTvVideo(): TvVideo? {
    if (type.isNotBlank() && type != "video") return null
    val id = videoId ?: return null
    val thumb = "https://i.ytimg.com/vi/$id/mqdefault.jpg"
    val dur = lengthSeconds?.let { if (it > 0) "%d:%02d".format(it / 60, it % 60) else "" } ?: ""
    val avatar = authorThumbnails?.firstOrNull()?.url
    return TvVideo(
        id = id,
        title = title ?: "Untitled",
        channelTitle = author ?: "Unknown",
        channelId = authorId ?: "",
        thumbnail = thumb,
        duration = dur,
        viewsText = viewCount?.takeIf { it > 0 }?.let { formatViews(it) },
        publishedText = publishedText,
        avatarUrl = fixThumbnailUrl(avatar),
        isLive = liveNow == true,
    )
}

private fun fixThumbnailUrl(url: String?): String? {
    if (url.isNullOrBlank()) return null
    // Invidious avatars may be http://yt.khoavo.myds.me or protocol-relative // — force https via i.ytimg proxy
    if (url.startsWith("http://yt.khoavo.myds.me")) return url.replace("http://", "https://")
    if (url.startsWith("//")) return "https:$url"
    return url
}

private fun formatViews(v: Long): String = when {
    v >= 1_000_000_000 -> "%.1fB views".format(v / 1_000_000_000.0)
    v >= 1_000_000 -> "%.1fM views".format(v / 1_000_000.0)
    v >= 1_000 -> "%.1fK views".format(v / 1_000.0)
    else -> "$v views"
}
